'use strict';

angular.module('copaamericaApp')
  .config(function ($translateProvider) {
    $translateProvider.translations('en', {
      //navbar
      BET: 'Bet',
      ADMIN: 'Admin',
      HOME: 'Home',
      TOURNAMENT: 'Tournament',
      BET_TABLE: 'Bet Table',
      HELLO_NAVBAR: 'Hello',
      LOGOUT: 'Logout',

      //settings
      CHANGE_PASSWORD_HEADER: 'Change Password',
      CURRENT_PASSWORD: 'Current Password',
      NEW_PASSWORD: 'New Password',
      NEW_PASSWORD_LENGTH: 'Password must be at least 3 characters.',
      NEW_PASSWORD_CONFIRM: 'Confirm New Password',
      NEW_PASSWORD_SUCCESS: 'Password successfully changed.',
      INCORRECT_PASSWORD: 'Incorrect password',
      NEW_PASSWORD_MATCH: 'Passwords must match.',
      EMPTY: '',
      SAVE_PASSWORD_BUTTON: 'Save Changes',

      //main
      MAKE_A_BET: 'Make a Bet!',
      ENGLISH: 'English',
      SPANISH: 'Spanish',
      LOGIN: 'Login',
      REGISTER: 'Register',
      EMAIL: 'Email',
      PASSWORD: 'Password',
      EMAIL_PASSWORD_MISSING: 'Please enter your email and password.',
      EMAIL_INVALID: 'Please enter a valid email.',
      EMAIL_REQUIRED: 'An Email is required.',
      NAME: 'Name',
      NAME_REQUIRED: 'A Name is required.',
      CONNECT_WITH: 'Connect with',
      PASSWORD_CONFIRM: 'Confirm Password',
      REGISTER_COLUMN: 'Register!',
      REGISTER_COLUMN_P1: 'Register (or log in) below by entering your data or just connect with',
      MAKE_A_BET_P1: 'Go ahead and bet on every match.',
      MAKE_A_BET_P2: 'You earn points by guessing winners (and even more for guessing the exact number of goals). You will also bet on the Golden Boot winner for even more points!',
      HOW_YOU_FARE: 'See how you fare!',
      HOW_YOU_FARE_P1: 'Check the Bet Table to compare your bet against the other players.',
      HOW_YOU_FARE_P2: 'See if you are ahead, and when you are, Brag on!',
      POINT_BREAKDOWN: 'Points Breakdown',
      MATCHES: 'Matches',
      MATCHES_P1: 'You can earn +2 points for each match by guessing the winner and +3 more points if you guess the exact result.',
      MATCHES_P2: 'With 32 matches you can earn a total of 160 points!',
      GROUPS: 'Groups',
      GROUPS_P1: 'If you guess correctly the team that comes in first place as well as the runner up of a group you can earn +5 points.',
      GROUPS_P2: 'There are 4 groups, that makes 20 points!',
      PODIUM_P1: 'Guess the teams that will be in the Podium and earn +25 points.',
      PODIUM_P2: 'But wait, There\'s more! If they are in the correct order you will get +35 more points. That\'s 70 points total!',
      GOLDEN_BOOT_P1: 'Pick your candidate for the Golden Boot and if you are right then you will get +50 points.',
      GOLDEN_BOOT_P2: 'If two or more players are tied for this award and your guess is one of them you still get the points!',
      TOTAL_P1: 'Add all the points for a total of 300 points!',
      WELCOME: 'Welcome to the Prode',

      //tournament
      GROUP_A: 'Group A',
      GROUP_B: 'Group B',
      GROUP_C: 'Group C',
      GROUP_D: 'Group D',
      POINTS_SHORT: 'Pts',
      GOALS_FOR_SHORT: 'GF',
      GOALS_AGAINST_SHORT: 'GA',
      GOAL_DIFFERENCE_SHORT: 'GD',

      //bet
      AWAY_GOALS: 'Away Goals',
      AWAY_PENALTIES: 'Away Penalties',
      AWAY_TEAM: 'Away',
      BET_ERROR: 'There is an error in this group of matches.',
      CONTINUE: 'Continue',
      DONE_BUTTON: 'Done',
      EDIT_BUTTON: 'Edit',
      EDIT_WARN: 'Are you sure? This will delete your Bet and you will have to start over!',
      EMPTY_BETS: 'There aren\'t any bets created yet.',
      FINALS: 'Final',
      FIRST_PLACE_PODIUM: '1st Place',
      GOLDEN_BOOT: 'Golden Boot',
      GOLDEN_BOOT_HEADER: 'Pick the Golden Boot winner (highest scorer of the tournament)',
      HOME_GOALS: 'Home Goals',
      HOME_PENALTIES: 'Home Penalties',
      HOME_TEAM: 'Home',
      ID: 'id',
      TEAM: 'Team',
      PLAYER: 'Player',
      PENALTIES: 'Penalties',
      PODIUM: 'Podium',
      QUARTER_FINALS: 'Quarter Finals',
      SAVE_BET_BUTTON: 'Save',
      SEMI_FINALS: 'Semi Finals',
      THIRD_PLACE: 'Third Place',
      RESTART_BUTTON: 'Start Over',
      RESTART_WARN: 'Are you sure? This will delete all your progress.',
      SECOND_PLACE_PODIUM: '2nd Place',
      THRID_PLACE_PODIUM: '3rd Place',
      USER: 'User',
      TOTAL: 'Total',
    });
  });
