'use strict';

angular.module('copaamericaApp')
  .config(function ($translateProvider) {
    $translateProvider.translations('es', {
      //admin
      INIT_DB: 'Inicializar BD',
      NOT_A_NUMBER: 'No es un número o fuera de rango!',
      UPDATE_MATCH: 'Actualizar Partido',
      SEARCH: 'Buscar',
      MATCH_ID: 'ID Partido',
      TEAM_ID: 'ID Equipo',
      GOALS: 'Goles',
      SCORERS: 'Goleadores',
      ADD_HOME_SCORER: 'Agregar Goleador Local',
      ADD_AWAY_SCORER: 'Agregar Goleador Visitante',
      SAVE: 'Guardar',
      SAVE_HOME_TEAM_SUCCESS: 'Equipo Local Guardado Exitósamente',
      SAVE_AWAY_TEAM_SUCCESS: 'Equipo Visitante Guardado Exitósamente',
      SAVE_HOME_TEAM_ERROR: 'Error al guardar Equipo Local',
      SAVE_AWAY_TEAM_ERROR: 'Error al guardar Equipo Visitante',
      SAVE_GROUP_SUCCESS: 'Grupo Guardado Exitósamente',
      SAVE_GROUP_ERROR: 'Error al guardar Grupo',

      //teams
      ARG: 'Argentina',
      BOL: 'Bolivia',
      BRA: 'Brasil',
      PER: 'Perú',
      PAN: 'Panamá',
      JAM: 'Jamaica',
      MEX: 'México',
      PAR: 'Paraguay',
      HAI: 'Haití',
      ECU: 'Ecuador',
      COS: 'Costa Rica',
      COL: 'Colombia',
      URU: 'Uruguay',
      USA: 'Estados Unidos',
      CHI: 'Chile',
      VEN: 'Venezuela',

      //navbar
      BET: 'Apuesta',
      ADMIN: 'Administrador',
      HOME: 'Inicio',
      TOURNAMENT: 'Torneo',
      BET_TABLE: 'Tabla de Apuestas',
      HELLO_NAVBAR: 'Hola',
      LOGOUT: 'Salir',

      //settings
      CHANGE_PASSWORD_HEADER: 'Cambiar Contraseña',
      CURRENT_PASSWORD: 'Contraseña Actual',
      NEW_PASSWORD: 'Contraseña Nueva',
      NEW_PASSWORD_LENGTH: 'La Contraseña debe tener al menos 3 caracteres.',
      NEW_PASSWORD_CONFIRM: 'Confirmar la nueva Contraseña',
      NEW_PASSWORD_SUCCESS: 'La Contraseña fue cambiada exitosamente.',
      INCORRECT_PASSWORD: 'Contraseña incorrecta',
      NEW_PASSWORD_MATCH: 'Las Contraseñas deben coincidir.',
      EMPTY: '',
      SAVE_PASSWORD_BUTTON: 'Guardar Cambios',

      //main
      MAKE_A_BET: 'Apostá!',
      ENGLISH: 'Inglés',
      SPANISH: 'Español',
      LOGIN: 'Ingresar',
      REGISTER: 'Registrar',
      EMAIL: 'Email',
      PASSWORD: 'Contraseña',
      EMAIL_PASSWORD_MISSING: 'Por favor, ingrese su Email y su Contraseña.',
      EMAIL_INVALID: 'Por favor, ingrese un Email válido.',
      EMAIL_REQUIRED: 'Por favor, ingrese un Email.',
      NAME: 'Nombre',
      NAME_REQUIRED: 'Por favor, ingrese un Nombre.',
      CONNECT_WITH: 'Ingresar con',
      PASSWORD_CONFIRM: 'Confirmar Contraseña',
      REGISTER_COLUMN: 'Registrate!',
      REGISTER_COLUMN_P1: 'Registrate (o Ingresá) abajo con tus datos o sólo ingresá con',
      MAKE_A_BET_P1: 'Hacé una apuesta por partido.',
      MAKE_A_BET_P2: 'Ganá puntos acertando ganadores o empates (y conseguí más puntos acertando la cantidad exacta de goles). También apostá por el ganador del Botín de Oro y ganá más puntos!',
      HOW_YOU_FARE: 'Compará puntos!',
      HOW_YOU_FARE_P1: 'Compará los resultados de tu apuesta con los de los demás jugadores.',
      HOW_YOU_FARE_P2: 'Fijate si vas primero y después echácelo en cara a todos!',
      POINT_BREAKDOWN: 'Distribución de los Puntos',
      MATCHES: 'Partidos',
      MATCHES_P1: 'Podés ganar +2 puntos por cada partido acertando el ganador (o el empate) y si además acertás el resultado ganas +3 puntos más.',
      MATCHES_P2: 'Con 32 partidos podés ganar un total de 160 puntos!',
      GROUPS: 'Grupos',
      GROUPS_P1: 'Si adivinás correctamente los equipos que terminan en primer y segundo puesto de un grupo podés sumar +5 puntos.',
      GROUPS_P2: 'Hay 4 grupos, eso suma 20 puntos!',
      PODIUM_P1: 'Acertá los equipos que conforman el Podio y ganá +25 puntos.',
      PODIUM_P2: 'Pero aún hay más! Si los equipos están en el orden correcto obtenés +35 puntos más. En total son 70 puntos!',
      GOLDEN_BOOT_P1: 'Elegí tu candidato para el Botín de Oro y si acertás sumás +50 puntos.',
      GOLDEN_BOOT_P2: 'Si dos o más jugadores están empatados en goles y elegiste uno de ellos, entonces obtenés los puntos igualmente!',
      TOTAL_P1: 'Sumá todos los puntos para un total de 300 puntos!',
      WELCOME: 'Bienvenido al Prode',

      //tournament
      GA: 'Grupo A',
      GB: 'Grupo B',
      GC: 'Grupo C',
      GD: 'Grupo D',
      Q1: 'Cuartos de Final 1',
      Q2: 'Cuartos de Final 2',
      Q3: 'Cuartos de Final 3',
      Q4: 'Cuartos de Final 4',
      S1: 'Semifinal 1',
      S2: 'Semifinal 2',
      TP: 'Tercer Puesto',
      F: 'Final',
      POINTS_SHORT: 'Pts',
      GOALS_FOR_SHORT: 'GF',
      GOALS_AGAINST_SHORT: 'GC',
      GOAL_DIFFERENCE_SHORT: 'GD',

      //bet
      AWAY_GOALS: 'Goles Visitante',
      AWAY_PENALTIES: 'Penales Visitante',
      AWAY_TEAM: 'Visitante',
      BET_ERROR: 'Hubo un error en este grupo de partidos.',
      CONTINUE: 'Continar',
      DONE_BUTTON: 'Listo',
      EDIT_BUTTON: 'Editar',
      EDIT_WARN: '¿Estás Seguro? Esto va a eliminar tu Apuesta y vas a tener que empezar de nuevo!',
      EMPTY_BETS: 'No hay apuestas creadas todavía.',
      FINALS: 'Final',
      FIRST_PLACE_PODIUM: '1er Lugar',
      GOLDEN_BOOT: 'Botín de Oro',
      GOLDEN_BOOT_HEADER: 'Elegí al ganador del Botín de Oro (goleador del torneo)',
      HOME_GOALS: 'Goles Local',
      HOME_PENALTIES: 'Penales Local',
      HOME_TEAM: 'Local',
      ID: 'id',
      MAKE_BET: 'Armá tu apuesta!',
      PLAYER: 'Jugador',
      PENALTIES: 'Penales',
      PODIUM: 'Podio',
      QUARTER_FINALS: 'Cuartos de Final',
      RESTART_BUTTON: 'Reiniciar',
      RESTART_WARN: '¿Estás Seguro? Esto va a eliminar todo tu progreso.',
      SAVE_BET_BUTTON: 'Guardar',
      SECOND_PLACE_PODIUM: '2do Lugar',
      SEMI_FINALS: 'Semifinales',
      STAGE: 'Etapa',
      TEAM: 'Equipo',
      THIRD_PLACE: 'Tercer Puesto',
      THRID_PLACE_PODIUM: '3er Lugar',
      USER: 'Usuario',
      TOTAL: 'Total',
      WARNING: 'Advertencia!'
    });
  });
