'use strict';

angular.module('copaamericaApp')
  .config(function ($translateProvider) {
    $translateProvider.translations('es', {
      //navbar
      BET: 'Apuesta',
      ADMIN: 'Administrador',
      HOME: 'Inicio',
      TOURNAMENT: 'Torneo',
      BET_TABLE: 'Tabla de Apuestas',
      HELLO_NAVBAR: 'Hola',
      LOGOUT: 'Salir',

      //settings
      CHANGE_PASSWORD_HEADER: 'Cambiar Contraseña',
      CURRENT_PASSWORD: 'Contraseña Actual',
      NEW_PASSWORD: 'Contraseña Nueva',
      NEW_PASSWORD_LENGTH: 'La Contraseña debe tener al menos 3 caracteres.',
      NEW_PASSWORD_CONFIRM: 'Confirmar la nueva Contraseña',
      NEW_PASSWORD_SUCCESS: 'La Contraseña fue cambiada exitosamente.',
      INCORRECT_PASSWORD: 'Contraseña incorrecta',
      NEW_PASSWORD_MATCH: 'Las Contraseñas deben coincidir.',
      EMPTY: '',
      SAVE_PASSWORD_BUTTON: 'Guardar Cambios',

      //main
      MAKE_A_BET: 'Apostá!',
      ENGLISH: 'Inglés',
      SPANISH: 'Español',
      LOGIN: 'Ingresar',
      REGISTER: 'Registrar',
      EMAIL: 'Email',
      PASSWORD: 'Contraseña',
      EMAIL_PASSWORD_MISSING: 'Por favor, ingrese su Email y su Contraseña.',
      EMAIL_INVALID: 'Por favor, ingrese un Email válido.',
      EMAIL_REQUIRED: 'Por favor, ingrese un Email.',
      NAME: 'Nombre',
      NAME_REQUIRED: 'Por favor, ingrese un Nombre.',
      CONNECT_WITH: 'Ingresar con',
      PASSWORD_CONFIRM: 'Confirmar Contraseña',
      REGISTER_COLUMN: 'Registrate!',
      REGISTER_COLUMN_P1: 'Registrate (o Ingresá) abajo con tus datos o sólo ingresá con',
      MAKE_A_BET_P1: 'Hacé una apuesta por partido.',
      MAKE_A_BET_P2: 'Ganá puntos acertando ganadores o empates (y conseguí más puntos acertando la cantidad exacta de goles). También apostá por el ganador del Botín de Oro y ganá más puntos!',
      HOW_YOU_FARE: 'Compará puntos!',
      HOW_YOU_FARE_P1: 'Compará los resultados de tu apuesta con los de los demás jugadores.',
      HOW_YOU_FARE_P2: 'Fijate si vas primero y después echácelo en cara a todos!',
      POINT_BREAKDOWN: 'Distribución de los Puntos',
      MATCHES: 'Partidos',
      MATCHES_P1: 'Podés ganar +2 puntos por cada partido acertando el ganador (o el empate) y si además acertás el resultado ganas +3 puntos más.',
      MATCHES_P2: 'Con 32 partidos podés ganar un total de 160 puntos!',
      GROUPS: 'Grupos',
      GROUPS_P1: 'Si adivinás correctamente los equipos que terminan en primer y segundo puesto de un grupo podés sumar +5 puntos.',
      GROUPS_P2: 'Hay 4 grupos, eso suma 20 puntos!',
      PODIUM_P1: 'Acertá los equipos que conforman el Podio y ganá +25 puntos.',
      PODIUM_P2: 'Pero aún hay más! Si los equipos están en el orden correcto obtenés +35 puntos más. En total son 70 puntos!',
      GOLDEN_BOOT_P1: 'Elegí tu candidato para el Botín de Oro y si acertás sumás +50 puntos.',
      GOLDEN_BOOT_P2: 'Si dos o más jugadores están empatados en goles y elegiste uno de ellos, entonces obtenés los puntos igualmente!',
      TOTAL_P1: 'Sumá todos los puntos para un total de 300 puntos!',
      WELCOME: 'Bienvenido al Prode',

      //tournament
      GROUP_A: 'Grupo A',
      GROUP_B: 'Grupo B',
      GROUP_C: 'Grupo C',
      GROUP_D: 'Grupo D',
      POINTS_SHORT: 'Pts',
      GOALS_FOR_SHORT: 'GF',
      GOALS_AGAINST_SHORT: 'GC',
      GOAL_DIFFERENCE_SHORT: 'GD',

      //bet
      AWAY_GOALS: 'Goles Visitante',
      AWAY_PENALTIES: 'Penales Visitante',
      AWAY_TEAM: 'Visitante',
      BET_ERROR: 'Hubo un error en este grupo de partidos.',
      CONTINUE: 'Continar',
      DONE_BUTTON: 'Listo',
      EDIT_BUTTON: 'Editar',
      EDIT_WARN: '¿Estás Seguro? Esto va a eliminar tu Apuesta y vas a tener que empezar de nuevo!',
      EMPTY_BETS: 'No hay apuestas creadas todavía.',
      FINALS: 'Final',
      FIRST_PLACE_PODIUM: '1er Lugar',
      GOLDEN_BOOT: 'Botín de Oro',
      GOLDEN_BOOT_HEADER: 'Elegí al ganador del Botín de Oro (goleador del torneo)',
      HOME_GOALS: 'Goles Local',
      HOME_PENALTIES: 'Penales Local',
      HOME_TEAM: 'Local',
      ID: 'id',
      TEAM: 'Equipo',
      PLAYER: 'Jugador',
      PENALTIES: 'Penales',
      PODIUM: 'Podio',
      QUARTER_FINALS: 'Cuartos de Final',
      RESTART_BUTTON: 'Reiniciar',
      RESTART_WARN: '¿Estás Seguro? Esto va a eliminar todo tu progreso.',
      SAVE_BET_BUTTON: 'Guardar',
      SECOND_PLACE_PODIUM: '2do Lugar',
      SEMI_FINALS: 'Semifinales',
      THIRD_PLACE: 'Tercer Puesto',
      THRID_PLACE_PODIUM: '3er Lugar',
      USER: 'Usuario',
      TOTAL: 'Total',
      WARNING: 'Warning!'
    });
  });
